// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47Yhe7qiroBkdZe2HO0cPio6_Hwdts2k',
    appId: '1:704467015877:web:38ef258392ab80fb42f8ac',
    messagingSenderId: '704467015877',
    projectId: 'que-comer-hoy-425e4',
    authDomain: 'que-comer-hoy-425e4.firebaseapp.com',
    storageBucket: 'que-comer-hoy-425e4.firebasestorage.app',
    measurementId: 'G-8ESVK6FTT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDHPnuCZEp5w0SxWy5kjQspZAwh1WChSc',
    appId: '1:704467015877:android:6baf56844fe3498942f8ac',
    messagingSenderId: '704467015877',
    projectId: 'que-comer-hoy-425e4',
    storageBucket: 'que-comer-hoy-425e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4H8hmq5idVi85bKWAWaddMq5u82r4dk',
    appId: '1:704467015877:ios:37e3ae2dd7bdbda542f8ac',
    messagingSenderId: '704467015877',
    projectId: 'que-comer-hoy-425e4',
    storageBucket: 'que-comer-hoy-425e4.firebasestorage.app',
    iosBundleId: 'com.example.queComerHoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4H8hmq5idVi85bKWAWaddMq5u82r4dk',
    appId: '1:704467015877:ios:37e3ae2dd7bdbda542f8ac',
    messagingSenderId: '704467015877',
    projectId: 'que-comer-hoy-425e4',
    storageBucket: 'que-comer-hoy-425e4.firebasestorage.app',
    iosBundleId: 'com.example.queComerHoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47Yhe7qiroBkdZe2HO0cPio6_Hwdts2k',
    appId: '1:704467015877:web:92d196d204f7302f42f8ac',
    messagingSenderId: '704467015877',
    projectId: 'que-comer-hoy-425e4',
    authDomain: 'que-comer-hoy-425e4.firebaseapp.com',
    storageBucket: 'que-comer-hoy-425e4.firebasestorage.app',
    measurementId: 'G-T82HEP1XJQ',
  );
}
